### PR TITLE
main yml for github actions

### PR DESCRIPTION
**Pull request by mozesjacobs**
@NelleV my main.yml file. it does not work - has problems with iced

### CODE REVIEW

**Comment by NelleV** [comment]
I don't know whether I fixed the issue or not. You need to add pytest to the list of packages installed (in `environment.yml`). The tests need to be ran from a different repository than root for them to work. Else, it tries to import pastis from the local repository, and the C dependencies have not be compiled there.

**Comment by mozesjacobs** [comment]
@NelleV I added pytest to environment.yml but it still has issues

**Comment by mozesjacobs** [comment]
@NelleV I added PyTest to environment.yml but it still isn't working. Not sure what's wrong with it.

**Comment by NelleV** [comment]
Superseded by #94

**Pull request closed without merging**
